# Generated by Django 2.0.3 on 2020-02-25 07:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200224_2330'),
    ]

    operations = [
        migrations.CreateModel(
            name='RightsSupport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('user_rights', 'User rights'), ('owner_rights', 'Owner rights')),
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='useraccounts',
            name='phone',
            field=models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Invalid format, ex: '+999999999'.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
