# Generated by Django 2.0.3 on 2020-02-27 11:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=60)),
                ('reg_no', models.CharField(max_length=30)),
                ('active', models.BooleanField(default=False)),
                ('permitted', models.BooleanField(default=False)),
                ('leave_day', models.CharField(choices=[('Sunday', 'Sunday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturay', 'Saturday')], max_length=15, null=True)),
                ('category', models.CharField(choices=[('ksrtc', 'KSRTC'), ('private', 'Private')], max_length=15)),
                ('ksrtc_category', models.CharField(choices=[('ORD', 'Ordinary'), ('LS', 'Limited Stop'), ('TT', 'Town to Town'), ('FS', 'Fast Passenger'), ('SF', 'Super Fast'), ('PP', 'Point to Point'), ('LF', 'Low Floor'), ('ALF', 'A/C Low Floor')], max_length=15, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlacesModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('place_name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RouteModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('stand_delay', models.PositiveIntegerField(default=0)),
                ('time', models.TimeField()),
                ('forward', models.BooleanField(default=True)),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus.PlacesModel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TripModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('active', models.BooleanField(default=False)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus.BusModel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='routemodel',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus.TripModel'),
        ),
    ]
