# Generated by Django 2.0.3 on 2020-02-27 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0002_auto_20200227_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busmodel',
            name='ksrtc_category',
            field=models.CharField(blank=True, choices=[('ORD', 'Ordinary'), ('LS', 'Limited Stop'), ('TT', 'Town to Town'), ('FS', 'Fast Passenger'), ('SF', 'Super Fast'), ('PP', 'Point to Point'), ('LF', 'Low Floor'), ('ALF', 'A/C Low Floor')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='busmodel',
            name='leave_day',
            field=models.CharField(blank=True, choices=[('Sunday', 'Sunday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturay', 'Saturday')], max_length=15, null=True),
        ),
    ]
