# Generated by Django 2.0.3 on 2020-03-07 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0004_auto_20200227_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripmodel',
            name='end_place',
            field=models.CharField(default='adivaram', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tripmodel',
            name='start_place',
            field=models.CharField(default='kozhikode', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='busmodel',
            name='category',
            field=models.CharField(choices=[('ksrtc', 'KSRTC'), ('private', 'Private')], default='private', max_length=15),
        ),
    ]
