# Generated by Django 2.0.3 on 2020-03-13 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0005_auto_20200307_0946'),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('category', models.CharField(choices=[('general', 'General Hospital'), ('government', 'Government Hospital'), ('private', 'Private Hospital')], default='general', max_length=20)),
                ('address', models.TextField(null=True)),
                ('phone', models.CharField(max_length=20, null=True)),
                ('latitude', models.CharField(max_length=100, null=True)),
                ('longitude', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PoliceStationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('address', models.TextField(null=True)),
                ('phone', models.CharField(max_length=20, null=True)),
                ('latitude', models.CharField(max_length=100, null=True)),
                ('longitude', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
