# Generated by Django 2.0.3 on 2020-03-13 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0007_auto_20200313_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nearmemodel',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
