# Generated by Django 2.0.3 on 2020-03-14 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0008_auto_20200313_1745'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyNumbersModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='nearmemodel',
            name='hospital_category',
            field=models.CharField(blank=True, choices=[('general', 'General Hospital'), ('government', 'Government Hospital'), ('private', 'Private Hospital')], max_length=20, null=True),
        ),
    ]
