# Generated by Django 2.0.3 on 2020-03-14 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0009_auto_20200314_1248'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentBusModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('owner', models.CharField(max_length=60)),
                ('reg_no', models.CharField(max_length=30)),
                ('category', models.CharField(blank=True, choices=[('minibus', 'Mini bus'), ('delux', 'Delux bus'), ('non-delux', 'Non-Delux bus')], max_length=20, null=True)),
                ('ac', models.BooleanField(default=True)),
                ('capacity', models.IntegerField(blank=True, null=True)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
