# Generated by Django 2.0.3 on 2020-03-15 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0012_auto_20200314_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='busmodel',
            name='booking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='busmodel',
            name='capacity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='busmodel',
            name='minimum_rate',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='busmodel',
            name='rate_hour',
            field=models.IntegerField(default=0),
        ),
    ]
