# Generated by Django 2.0.3 on 2020-03-15 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0013_auto_20200315_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busmodel',
            name='minimum_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='busmodel',
            name='rate_hour',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
