# Generated by Django 2.0.3 on 2020-03-15 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0014_auto_20200315_2015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='busmodel',
            name='leave_day',
        ),
    ]
