# Generated by Django 2.0.3 on 2020-03-16 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0016_bookingmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingmodel',
            name='trip',
        ),
        migrations.RemoveField(
            model_name='bookingmodel',
            name='user',
        ),
        migrations.DeleteModel(
            name='BookingModel',
        ),
    ]
