# Generated by Django 2.0.3 on 2020-03-16 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0018_bookingmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingmodel',
            name='end',
            field=models.ForeignKey(default=45, on_delete=django.db.models.deletion.CASCADE, related_name='tripend', to='bus.RouteModel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookingmodel',
            name='fare',
            field=models.IntegerField(default=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookingmodel',
            name='start',
            field=models.ForeignKey(default=14, on_delete=django.db.models.deletion.CASCADE, related_name='tripstart', to='bus.RouteModel'),
            preserve_default=False,
        ),
    ]
